stages:
  preprocess:
    cmd: python src/preprocess.py
    deps:
      - src/preprocess.py
      - ${data.path}
      - params.yaml
    outs:
      - data/processed/X_train.csv
      - data/processed/X_test.csv
      - data/processed/y_train.csv
      - data/processed/y_test.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/X_train.csv
      - data/processed/y_train.csv
      - params.yaml
    outs:
      - models/best_model.joblib
      - models/best_model_info.json

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/best_model.joblib
      - models/best_model_info.json
      - data/processed/X_test.csv
      - data/processed/y_test.csv
      - params.yaml
    metrics:
      - metrics.json:
          cache: false

