data:
  path: "data/raw/dataset_v3.csv"
  target: "MedHouseVal"
  test_size: 0.2
  random_state: 42

models:
  linear_regression:
    type: "linear_regression"
    params: {}
  random_forest:
    type: "random_forest"
    params:
      n_estimators: 100
      max_depth: 5
      random_state: 42

metrics:
  primary: "rmse"
  others: ["r2"]

